apiVersion: v1
kind: Template
parameters:
  - name: APP_IMAGE
    value:
metadata:
  name: greeting-template
  annotations:
    description: "Template per il deploy del frontend in Angular"
  namespace: app-inglese
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: greeting-fe
      labels:
        app: greeting
      namespace: app-inglese
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: greeting
      template:
        metadata:
          labels:
            app: greeting
        spec:
          serviceAccountName: pipeline
          containers:
          - env:
            - name: SALUTI
              valueFrom:
                configMapKeyRef:
                  name: greeting-fe
                  key: SALUTI
            image: ${APP_IMAGE}
            imagePullPolicy: Always
            name: greeting-fe
            ports:
              - containerPort: 8081
  - kind: Service
    apiVersion: v1
    metadata:
      name: greeting-fe
      labels:
        app: greeting
      namespace: app-inglese
    spec:
      ports:
      - port: 8081
      selector:
        app: greeting
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: greeting-fe
      name: greeting-fe-route
      namespace: app-inglese
    spec:
      to:
        kind: Service
        name: greeting-fe
